### PR TITLE
feat: competitive onboarding

### PR DESCRIPTION
**Pull request by 0xhank**

### CODE REVIEW

**Comment by cha0sg0d** [comment]
@henryacaron This is nice and clean. One thing -> I want balances displayed when you choose account.

**Comment by cha0sg0d** [comment]
Also @henryacaron we need to keep the Faucet drip logic.

`Creating new arena instance...FAILED` if xDai balance too low

**Comment by cha0sg0d** [comment]
We should remove spectator mode here -> it's not possible to spectate without the right url. So you can send someone the link and they can spectate. But they can't join as a spectator via `Solo Challenge`

**Comment by 0xhank** [comment]
> @henryacaron This is nice and clean. One thing -> I want balances displayed when you choose account.

this is something that david is working on, i just wanted to add the basic functionality and he will come in and make it look good

**Comment by 0xhank** [comment]
> We should remove spectator mode here -> it's not possible to spectate without the right url. So you can send someone the link and they can spectate. But they can't join as a spectator via `Solo Challenge`

why cant you join as spectator via solo challenge? the url automatically updates to the correct address so if you copy that address it will work. additionally, this is the landing pagefor any game, not just competitive, so the change will affect all games. we could have a check for competitive and remove spectator mode, but it doesnt seem super necessary

**Pull request merged**
